CREATE TABLE "POST" (
	"POST_NO"	NUMBER		PRIMARY KEY,
	"POST_TITLE"	VARCHAR2(200)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"REPORT_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"VIOLATION_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"LIKE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"MODIFY_DT"	DATE	DEFAULT SYSDATE	NOT NULL
--	"BLOG_NO"	NUMBER		NOT NULL,
--	"CATRGOEY_CD"	NUMBER		NOT NULL,
--	"BOARD_STATUS_CD"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "POST"."POST_NO" IS '게시글 번호';

COMMENT ON COLUMN "POST"."POST_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "POST"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "POST"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "POST"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "POST"."REPORT_COUNT" IS '신고수';

COMMENT ON COLUMN "POST"."VIOLATION_COUNT" IS '경고수';

COMMENT ON COLUMN "POST"."LIKE_COUNT" IS '좋아요수';

COMMENT ON COLUMN "POST"."MODIFY_DT" IS '수정일';

--COMMENT ON COLUMN "POST"."BLOG_NO" IS '블로그 번호';
--
--COMMENT ON COLUMN "POST"."CATRGOEY_CD" IS '카테고리 코드';
--
--COMMENT ON COLUMN "POST"."BOARD_STATUS_CD" IS '게시글 상태 코드';








